// <auto-generated />
namespace ReviewsCalculateSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DATABASE_UPDATE_FROM_MY_PC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DATABASE_UPDATE_FROM_MY_PC));
        
        string IMigrationMetadata.Id
        {
            get { return "201902251625064_DATABASE_UPDATE_FROM_MY_PC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
